### ISSUE TITLE
HyperPixel 4 is stucks at boot "Registred framebuffer for display 0, 480x800" and won't load CLI or UI

### ISSUE THREAD

**Issue by giuliomagnifico** [pimoroni/hyperpixel4#103]
**Describe the bug**

I can't display PADD (Pi-Hole graphic stats) or nothing else after I installed the driver for Pimoroni Display HyperPixel 4

![IMG_6573](https://user-images.githubusercontent.com/1975176/94057488-f8af6500-fddf-11ea-9714-d686eff5503a.jpeg)

**To Reproduce**

Installed via Github the correct driver form my non touch display rectangular

**Your HyperPixel 4**

Last versione: 60fps 800x480 and sdi connection

1. Is it Square or Rectangular?

Rectangular
2. Touch or non Touch?
Non touch
3. Approximately when was it purchased
yesterday
4. How is it connected to your Pi
via GPiO interface

**Your Raspberry Pi**
RPi 4B

Give as much detail about your Pi and OS as possible. We only officially support Raspbian, but might be able to point you in the right direction if the problem is with another OS.

1. What model of Raspberry Pi are you using (the result of `cat /proc/cpuinfo | grep Revision` can tell us this exactly
**Revision        : c03112**
2. Which OS release are you using: `lsb_release --description` and `uname -r`
**Raspbian GNU/Linux 10 (buster)** + **5.4.51-v7l+**
3. Is this a fresh OS setup, or one you might have previously installed scripts/add-ons on?
I have and old display with  “_LCD35-Show_” drivers that I unistalled with `sudo rm -rf LCD-show`

**Extra debugging information**

If you're having a problem with touch, try checking `dmesg` for related errors:
no touch here

My config.txt file

```
# For more options and information see
# http://rpf.io/configtxt
# Some settings may impact device functionality. See link above for details
# uncomment if you get no picture on HDMI for a default "safe" mode
#hdmi_safe=1
# uncomment this if your display has a black border of unused pixels visible
# and your display can output without overscan
disable_overscan=1
# uncomment the following to adjust overscan. Use positive numbers if console
# goes off screen, and negative if there is too much border
#overscan_left=16
#overscan_right=16
#overscan_top=16
#overscan_bottom=16
# uncomment to force a console size. By default it will be display's size minus
# overscan.
#framebuffer_width=1280
#framebuffer_height=720
# uncomment if hdmi display is not detected and composite is being output
hdmi_force_hotplug=1
# uncomment to force a specific HDMI mode (this will force VGA)
hdmi_group=2
hdmi_mode=4
# uncomment to force a HDMI mode rather than DVI. This can make audio work in
# DMT (computer monitor) modes
#hdmi_drive=2
# uncomment to increase signal to HDMI, if you have interference, blanking, or
# no display
#config_hdmi_boost=4
# uncomment for composite PAL
#sdtv_mode=2
#uncomment to overclock the arm. 700 MHz is the default.
#arm_freq=800
# Uncomment some or all of these to enable the optional hardware interfaces
#dtparam=i2c_arm=on
#dtparam=i2s=on
#dtparam=spi=on
# Uncomment this to enable infrared communication.
#dtoverlay=gpio-ir,gpio_pin=17
#dtoverlay=gpio-ir-tx,gpio_pin=18
# Additional overlays and parameters are documented /boot/overlays/README
# Enable audio (loads snd_bcm2835)
dtparam=audio=on
[pi4]

# Enable DRM VC4 V3D driver on top of the dispmanx display stack
#dtoverlay=vc4-fkms-v3d
max_framebuffers=2
[all]
dtoverlay=hyperpixel4
enable_dpi_lcd=1
dpi_group=2
dpi_mode=87
dpi_output_format=0x7f216
dpi_timings=480 0 10 16 59 800 0 15 113 15 0 0 0 60 0 32000000 6

Thanks for the help!
```

**Comment by giuliomagnifico** [comment]
Okay, I went able to boot but not to rotate correctly the display.

![IMG_6574](https://user-images.githubusercontent.com/1975176/94063487-79725f00-fde8-11ea-8b3c-9c372a19cce7.jpeg)


> pi@pi-hole:~ $ hyperpixel4-rotate left
> Rotating display
> Can't open display 
> Traceback (most recent call last):
>   File "<stdin>", line 15, in <module>
>   File "/usr/lib/python2.7/dist-packages/screenlayout/xrandr.py", line 43, in __init__
>     version_output = self._output("--version")
>   File "/usr/lib/python2.7/dist-packages/screenlayout/xrandr.py", line 64, in _output
>     raise Exception("XRandR returned error code %d: %s"%(status,err))
> Exception: XRandR returned error code 1: Can't open display 
> 
> Setting matrix: 0 -1 1 1 0 0
> Unable to connect to X server
> Saving touch settings to /etc/udev/rules.d/98-hyperpixel4-calibration.rules
> pi@pi-hole:~ $ 

And my config.txt in /boot


> dtoverlay=hyperpixel4,display_lcd_rotate=1
> framebuffer_width=480
> framebuffer_height=800
> enable_dpi_lcd=1
> dpi_group=2
> dpi_mode=87
> dpi_output_format=0x7f216
> dpi_timings=480 0 10 16 59 800 0 15 113 15 0 0 0 60 0 32000000 6
> start_x=0
>

**Comment by giuliomagnifico** [comment]
Oksy i solved by using "_display_rotate=3_"
