### ISSUE TITLE
HyperPixel 4.0 Rectangular rotation

### ISSUE THREAD

**Issue by wudave** [pimoroni/hyperpixel4#132]
**Describe the bug**
Cannot rotation the display and after manually install the driver, the display went completely black

What's gone wrong?
1. I purchased Pi-400 and Adafruit CYBERDECK HAT (https://www.adafruit.com/product/4863) to connect to HyperPixel 4.0.  Tried "hyperpixel4-rotate left" command but getting below error message:
pi@raspberrypi:~ $ DISPLAY=:0.0
pi@raspberrypi:~ $ hyperpixel4-rotate left
Rotating display
Can't open display 
Traceback (most recent call last):
  File "<stdin>", line 15, in <module>
  File "/usr/lib/python2.7/dist-packages/screenlayout/xrandr.py", line 43, in __init__
    version_output = self._output("--version")
  File "/usr/lib/python2.7/dist-packages/screenlayout/xrandr.py", line 64, in _output
    raise Exception("XRandR returned error code %d: %s"%(status,err))
Exception: XRandR returned error code 1: Can't open display 

Setting matrix: 0 -1 1 1 0 0
Unable to connect to X server
Saving touch settings to /etc/udev/rules.d/98-hyperpixel4-calibration.rules

2. I then followed instructions (https://github.com/pimoroni/hyperpixel4/tree/pi4) to manually install but the display went completely black.

**To Reproduce**

What install steps did you go through so far? Did you install from GitHub or use our one-line-installer?
Tried one-line-installer, the diplay came out to be portrait mode.  I then followed instructions (https://github.com/pimoroni/hyperpixel4/tree/pi4) to manually install but the display went completely black.

**Your HyperPixel 4**

Let us know which HyperPixel 4 board you're using. Note: if you're having a problem with the original HyperPixel you should go to: https://github.com/pimoroni/hyperpixel

1. Is it Square or Rectangular? -> Rectangular
2. Touch or non Touch? -> Touch
3. Approximately when was it purchased -> 2 weeks ago
4. How is it connected to your Pi -> 

**Your Raspberry Pi**

Give as much detail about your Pi and OS as possible. We only officially support Raspbian, but might be able to point you in the right direction if the problem is with another OS.

1. What model of Raspberry Pi are you using (the result of `cat /proc/cpuinfo | grep Revision` can tell us this exactly -> pi@raspberrypi:~ $ cat /proc/cpuinfo | grep Revision
Revision	: c03130
2. Which OS release are you using: `lsb_release --description` and `uname -r` -> pi@raspberrypi:~ $ lsb_release --description
Description:	Raspbian GNU/Linux 10 (buster)
pi@raspberrypi:~ $ uname -r
5.10.17-v7l+

3. Is this a fresh OS setup, or one you might have previously installed scripts/add-ons on? -> fresh OS

**Extra debugging information**

Debug log:
pi@raspberrypi:~ $ curl -sSL https://raw.githubusercontent.com/pimoroni/hyperpixel4/master/hyperpixel4-debug.sh | bash

## Platform Information

Revision	: c03130
Description:	Raspbian GNU/Linux 10 (buster)
5.10.17-v7l+

## Touchscreen logs

Rectangular: Goodix
[    7.176470] Goodix-TS 11-0014: supply AVDD28 not found, using dummy regulator
[    7.176856] Goodix-TS 11-0014: supply VDDIO not found, using dummy regulator
[    7.185484] Goodix-TS 11-0014: ID 911, version: 1060
[    7.275522] input: Goodix Capacitive TouchScreen as /devices/platform/i2c@0/i2c-11/11-0014/input/input3
Square: ft5

## I2C Devices and Mappings

/dev/i2c-1
/dev/i2c-11
     0  1  2  3  4  5  6  7  8  9  a  b  c  d  e  f
00:          -- -- -- -- -- -- -- -- -- -- -- -- -- 
10: -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- 
20: -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- 
30: -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- 
40: -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- 
50: -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- 
60: -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- 
70: -- -- -- -- -- -- -- --                         

## Boot Config

# For more options and information see
# http://rpf.io/configtxt
# Some settings may impact device functionality. See link above for details

# uncomment if you get no picture on HDMI for a default "safe" mode
hdmi_safe=1

# uncomment this if your display has a black border of unused pixels visible
# and your display can output without overscan
disable_overscan=1

# uncomment the following to adjust overscan. Use positive numbers if console
# goes off screen, and negative if there is too much border
#overscan_left=16
#overscan_right=16
#overscan_top=16
#overscan_bottom=16

# uncomment to force a console size. By default it will be display's size minus
# overscan.
#framebuffer_width=480
#framebuffer_height=800

# uncomment if hdmi display is not detected and composite is being output
#hdmi_force_hotplug=1

# uncomment to force a specific HDMI mode (this will force VGA)
#hdmi_group=1
#hdmi_mode=1

# uncomment to force a HDMI mode rather than DVI. This can make audio work in
# DMT (computer monitor) modes
#hdmi_drive=2

# uncomment to increase signal to HDMI, if you have interference, blanking, or
# no display
config_hdmi_boost=4

# uncomment for composite PAL
#sdtv_mode=2

#uncomment to overclock the arm. 700 MHz is the default.
#arm_freq=800

# Uncomment some or all of these to enable the optional hardware interfaces
dtparam=i2c_arm=on
#dtparam=i2s=on
dtparam=spi=on

# Uncomment this to enable infrared communication.
#dtoverlay=gpio-ir,gpio_pin=17
#dtoverlay=gpio-ir-tx,gpio_pin=18

# Additional overlays and parameters are documented /boot/overlays/README

# Enable audio (loads snd_bcm2835)
dtparam=audio=on

[pi4]
# Enable DRM VC4 V3D driver on top of the dispmanx display stack
dtoverlay=vc4-fkms-v3d
max_framebuffers=2

[all]
#dtoverlay=vc4-fkms-v3d
start_x=1
gpu_mem=128
dtoverlay=w1-gpio

dtoverlay=hyperpixel4:rotate
display_rotate=1
enable_dpi_lcd=1
dpi_group=2
dpi_mode=87
dpi_output_format=0x7f216
dpi_timings=480 0 10 16 59 800 0 15 113 15 0 0 0 60 0 32000000 6
enable_uart=1

If you're having a problem with touch, try checking `dmesg` for related errors:

* `dmesg | grep Goodix` for HyperPixel 4.0" Rectangular
* `dmesg | grep ft5` for HyperPixel 4.0" Square

And check i2c is working:

`ls /dev/i2c-*`

You should see something like:

```text
pi@raspberrypi:~ $ ls /dev/i2c-*
/dev/i2c-7
```

And your HyperPixel 4 touch is showing up (there should be an address blocked out with UU in the below command):

`i2cdetect -y X` ( where X is the number of i2c bus found in the command above)

For example:

```text
pi@raspberrypi:~ $ i2cdetect -y 7
     0  1  2  3  4  5  6  7  8  9  a  b  c  d  e  f
00:          -- -- -- -- -- -- -- -- -- -- -- -- --
10: -- -- -- -- UU -- -- -- -- -- -- -- -- -- -- --
20: -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- --
30: -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- --
40: -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- --
50: -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- --
60: -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- --
70: -- -- -- -- -- -- -- --
```

**Comment by wudave** [comment]
I re-ran
`curl -sSL https://get.pimoroni.com/hyperpixel4 | bash`
 Rebooted and connected to a monitor (instead of SSH).  It finally worked with below command.
`hyperpixel4-rotate left`

Closing ticket.
