### ISSUE TITLE
Unable to rotate the touch trough SSH on Pi4

### ISSUE THREAD

**Issue by GamezombieCZ** [pimoroni/hyperpixel4#143]
### When installing the driver on Raspbian (Raspberry Pi OS) through SSH and trying to rotate the display I get this output:
```
This rotate utility only works with the Raspberry Pi OS desktop version.
Rotating display
Traceback (most recent call last):
  File "<stdin>", line 15, in <module>
  File "/usr/lib/python2.7/dist-packages/screenlayout/xrandr.py", line 43, in __init__
    version_output = self._output("--version")
  File "/usr/lib/python2.7/dist-packages/screenlayout/xrandr.py", line 64, in _output
    raise Exception("XRandR returned error code %d: %s"%(status,err))
Exception: XRandR returned error code 1: No protocol specified
Can't open display :0.0
```
I tried to make changes to /boot/config.txt:
```
[pi4]
# Enable DRM VC4 V3D driver on top of the dispmanx display stack
dtoverlay=hyperpixel4:rotate
max_framebuffers=2

[all]
#dtoverlay=vc4-fkms-v3d

display_rotate=3

dtoverlay=hyperpixel4-common
dtoverlay=hyperpixel4-0x14
dtoverlay=hyperpixel4-0x5d
enable_dpi_lcd=1
dpi_group=2
dpi_mode=87
dpi_output_format=0x7f216
dpi_timings=480 0 10 16 59 800 0 15 113 15 0 0 0 60 0 32000000 6
```
I also added this line at the end in **/etc/rc.local**: `/usr/bin/hyperpixel4-rotate left`

**I get to rotate the display but never the touch.**

**Mine HyperPixel 4**

1. Rectangular
2. Touch
3. Purchased aprox. 2 months ago, I was waiting for functional MicroSD card.
4. Display is connected directly through GPIO header.

**Mine Raspberry Pi**
Raspberry Pi 4B Rev. 1.2 c03112
Raspberry Pi OS 2021-05-07 with the Raspberry Pi Desktop
I did Installed fully functioning OctoPrint before the driver installation

No related errors with the touch.

i2c is working & output is `/dev/i2c-11`

```
~ $ i2cdetect -y 11
     0  1  2  3  4  5  6  7  8  9  a  b  c  d  e  f
00:          -- -- -- -- -- -- -- -- -- -- -- -- --
10: -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- --
20: -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- --
30: -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- --
40: -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- --
50: -- -- -- -- -- -- -- -- -- -- -- -- -- UU -- --
60: -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- --
70: -- -- -- -- -- -- -- --
```

**Comment by GamezombieCZ** [comment]
`export XAUTHORITY=/home/pi/.Xauthority`
Might fix it, I'm not sure.
I'm really bad at making notes.
