### ISSUE TITLE
Screen wont rotate with RPI4 and Raspbian Buster dist-upgrade

### ISSUE THREAD

**Issue by purist69** [pimoroni/hyperpixel4#64]
I have an RPi4 with with a Hyperpixel 4 Touch which was working fine.  I decided to do a apt-get dist-upgrade...  The screen then reverted to the default orientation of 480x800 in portrait mode.  I issued the command 'hyperpixel4-rotate left' and it errorred out, so I uninstalled and reinstalled the drivers, however the same issues is occurring.  The error is below, any help would be appreciated.

Thanks!

hyperpixel4-rotate left
Rotating display
Can't open display
Traceback (most recent call last):
  File "<stdin>", line 15, in <module>
  File "/usr/lib/python2.7/dist-packages/screenlayout/xrandr.py", line 43, in __init__
    version_output = self._output("--version")
  File "/usr/lib/python2.7/dist-packages/screenlayout/xrandr.py", line 64, in _output
    raise Exception("XRandR returned error code %d: %s"%(status,err))
Exception: XRandR returned error code 1: Can't open display

Setting matrix: 0 -1 1 1 0 0
Unable to connect to X server
Saving touch settings to /etc/udev/rules.d/98-hyperpixel4-calibration.rules

**Comment by purist69** [comment]
already in item 51
